import javax.lang.model.element.Name

fun main()
{
    print("Enter Enrollment No : ")
    var Enroll= readLine()
    print("Enter Name : ")
    var Name= readLine()
    print("Enter Branch : ")
    var Branch= readLine()
    print("Enter Class : ")
    var Class= readLine()
    print("Enter Batch : ")
    var Batch= readLine()
    print("Enter College Name : ")
    var CollegeName= readLine()
    print("Enter University Name : ")
    var UniversityName= readLine()
    print("Enter Age : ")
    var Age= readLine()

    println("\nStudent Data : \n")
    println("Enrollment No : $Enroll")
    println("Name : $Name")
    println("Branch : $Branch")
    println("Class : $Class")
    println("Batch : $Batch")
    println("College Name : $CollegeName")
    println("University Name : $UniversityName")
    println("Age : $Age")
}